### ISSUE TITLE
runnodes jar throws "IOException: Cannot run program xterm" 

### ISSUE THREAD

**Issue by CluEleSsUK** [corda/samples-kotlin#30]
Hi there,

I am trying to run the sample found at https://docs.corda.net/docs/corda-os/4.7/tutorial-cordapp.html

I have successfully cloned the repo and generated the nodes with `./gradlew deployNodes`
When attempting to `java -jar runnodes.jar` I get the following output:

```
$ java -jar runnodes.jar 
base debug port set to： 5005
base monitoring port set to: 7005
Starting nodes in /somewhere/samples-kotlin/Basic/cordapp-example/build/nodes
No file corda.jar found in /somewhere/samples-kotlin/Basic/cordapp-example/build/nodes/.cache
Starting corda.jar in /somewhere/samples-kotlin/Basic/cordapp-example/build/nodes/PartyA on debug port 5005
Node will expose jolokia monitoring port on 7005
Running command: xterm -T PartyA -e '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java' '-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -javaagent:drivers/jolokia-jvm-1.6.0-agent.jar=port=7005,logHandlerClass=net.corda.node.JolokiaSlf4jAdapter' '-Dname=PartyA' '-jar' '/somewhere/samples-kotlin/Basic/cordapp-example/build/nodes/PartyA/corda.jar'; [ $? -eq 0 -o $? -eq 143 ] || sh
Exception in thread "main" java.io.IOException: Cannot run program "xterm" (in directory "/somewhere/Basic/cordapp-example/build/nodes/PartyA"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.corda.plugins.NodeRunner.startWindowed(NodeRunner.kt:133)
        at net.corda.plugins.NodeRunner.startJar(NodeRunner.kt:94)
        at net.corda.plugins.NodeRunner.startNode(NodeRunner.kt:73)
        at net.corda.plugins.NodeRunner.run(NodeRunner.kt:56)
        at net.corda.plugins.NodeRunnerKt.main(NodeRunner.kt:43)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 5 more
```

Some other useful info:
```
 $ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
 ```
 
 ```
$ uname -a
Linux somebody 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AndryOliinyk** [comment]
Fased with same issue, just install `xterm`:
`sudo apt install xterm`
